# Generated by Django 2.2.1 on 2019-06-01 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, max_length=30)),
                ('projects', models.TextField(blank=True, max_length=500)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('starting_date', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('subject', models.TextField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('company_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=100)),
                ('years', models.IntegerField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekone', models.IntegerField(blank=True, null=True)),
                ('weektwo', models.IntegerField(blank=True, null=True)),
                ('weekthree', models.IntegerField(blank=True, null=True)),
                ('weekfour', models.IntegerField(blank=True, null=True)),
                ('weekfive', models.IntegerField(blank=True, null=True)),
                ('weeksix', models.IntegerField(blank=True, null=True)),
                ('weekseven', models.IntegerField(blank=True, null=True)),
                ('weekeight', models.IntegerField(blank=True, null=True)),
                ('weeknine', models.IntegerField(blank=True, null=True)),
                ('weekten', models.IntegerField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Student'),
        ),
    ]
