# Generated by Django 2.2.1 on 2019-06-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_one_test', models.TextField()),
                ('week_two_test', models.TextField()),
                ('week_three_test', models.TextField()),
                ('week_four_test', models.TextField()),
                ('week_five_test', models.TextField()),
                ('week_six_test', models.TextField()),
                ('week_seven_test', models.TextField()),
                ('week_eight_test', models.TextField()),
                ('week_nine_test', models.TextField()),
                ('week_ten_test', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_one_material', models.TextField()),
                ('week_two_material', models.TextField()),
                ('week_three_material', models.TextField()),
                ('week_four_material', models.TextField()),
                ('week_five_material', models.TextField()),
                ('week_six_material', models.TextField()),
                ('week_seven_material', models.TextField()),
                ('week_eight_material', models.TextField()),
                ('week_nine_material', models.TextField()),
                ('week_ten_material', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBank.Course')),
            ],
        ),
    ]
