# Generated by Django 2.2.1 on 2019-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBank', '0002_coursematerials_coursetests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
