# Generated by Django 2.2.1 on 2019-06-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBank', '0004_remove_student_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='business',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
