# Generated by Django 2.2.1 on 2019-06-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBank', '0005_auto_20190603_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_eight_material',
            new_name='week_eight',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_five_material',
            new_name='week_five',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_four_material',
            new_name='week_four',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_nine_material',
            new_name='week_nine',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_one_material',
            new_name='week_one',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_seven_material',
            new_name='week_seven',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_six_material',
            new_name='week_six',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_ten_material',
            new_name='week_ten',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_three_material',
            new_name='week_three',
        ),
        migrations.RenameField(
            model_name='coursematerials',
            old_name='week_two_material',
            new_name='week_two',
        ),
    ]
