# Generated by Django 2.2.1 on 2019-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBank', '0006_auto_20190603_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
